name: deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release-pypi:
    name: release-pypi
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Build
        run: |
          pip install build
          python -m build
      - name: Upload to Pypi
        if: github.ref == 'refs/heads/main'
        run: |
          pip install twine
          twine upload --username __token__ --password ${{ secrets.PYPI_TOKEN }} dist/*
